import { recommended } from "@effect/tsgo/oxlint-presets";
import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  pack: {
    entry: ["src/index.ts", "src/async-await.ts"],
    deps: { neverBundle: [/^effect(?:\/|$)/] },
    dts: {
      tsgo: true,
    },
    exports: false,
  },
  lint: {
    extends: [recommended],
    overrides: [
      {
        files: [
          "src/async-await.ts",
          "src/client-runtime.ts",
          "src/client-response.ts",
          "src/client-errors.ts",
        ],
        rules: { "automation/private-function-prefix": "off" },
      },
      {
        files: ["src/async-await.ts", "src/client-runtime.ts", "src/client-response.ts"],
        rules: {
          "effecttsgo/async-function": "off",
          "automation/no-try-catch": "off",
          "automation/no-optional-function-parameters": "off",
          "automation/no-multiple-function-params": "off",
        },
      },
      {
        files: ["src/client-errors.ts"],
        rules: { "effecttsgo/extends-native-error": "off" },
      },
      {
        files: ["tests/async-*.test.ts", "tests/integration/async-client.test.ts"],
        rules: {
          "effecttsgo/async-function": "off",
          "automation/no-multiple-function-params": "off",
        },
      },
      {
        files: ["tests/**/*.test.ts"],
        rules: { "effecttsgo/strict-effect-provide": "off" },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: "anti-slop",
        specifier: "./tools/oxlint/anti-slop/index.mjs",
      },
      {
        name: "anti-slop-effect",
        specifier: "./tools/oxlint/anti-slop/effect/index.mjs",
      },
      {
        name: "automation",
        specifier: "./tools/oxlint/automation/index.mjs",
      },
      {
        name: "better-tailwindcss",
        specifier: "eslint-plugin-better-tailwindcss",
      },
    ],
    ignorePatterns: [
      "tools/diff-check/**",
      "tools/typed-lint/**",
      "tools/oxlint/anti-slop/**",
      "tools/oxlint/automation/**",
    ],
    rules: {
      ...Object.fromEntries(
        Object.keys(recommended.rules ?? {}).map((rule) => [rule, "error" as const]),
      ),
      "effecttsgo/strict-effect-provide": "error",
      "no-underscore-dangle": "off",
      "no-console": "error",
      "no-empty": "error",
      "no-empty-function": "error",
      "no-eq-null": "error",
      "no-unused-vars": "error",
      "unicorn/filename-case": "error",
      "require-yield": "off",
      "no-shadow": "off",
      "no-img-element": "off",
      "react-in-jsx-scope": "off",
      "exhaustive-deps": "off",
      "anti-slop/no-chained-type-assertions": "error",
      "anti-slop/no-conditional-empty-array-spread": "error",
      "automation/no-ambient-nondeterminism": "error",
      "automation/no-api-backend-imports": "error",
      "automation/no-api-repository-imports": "error",
      "automation/no-banned-type-assertions": "error",
      "automation/no-cascading-layer-provide": "error",
      "automation/no-comments": "error",
      "automation/no-css-modules": "error",
      "automation/no-direct-browser-storage": "error",
      "automation/no-direct-fetch": "error",
      "automation/no-direct-xstate-create-machine": "error",
      "automation/no-direct-xstate-use-selector": "error",
      "automation/no-disable-validation": "error",
      "automation/no-effect-asvoid": "error",
      "automation/no-global-json": "error",
      "automation/no-in-operator": "error",
      "automation/no-jsx-style": "error",
      "automation/no-fixed-height-on-content": "error",
      "automation/no-multiple-function-params": "error",
      "automation/no-multiple-xstate-hooks": "error",
      "automation/no-nested-effect-array-methods": "error",
      "automation/no-nested-layer-provide": "error",
      "automation/no-non-route-layout-files": "error",
      "automation/no-optional-function-parameters": "error",
      "automation/no-reexport-only-modules": "error",
      "automation/no-react-component-inner-functions": "error",
      "automation/no-react-non-component-function-exports": "error",
      "automation/no-react-state-hooks": "error",
      "automation/no-service-option": "error",
      "automation/no-shadowed-standard-array-static": "error",
      "automation/no-silent-error-swallow": "error",
      "automation/no-static-effect-service-forwarders": "error",
      "automation/no-single-use-private-functions": "error",
      "automation/no-single-use-xstate-actions": "error",
      "automation/no-single-use-xstate-guards": "error",
      "automation/no-sql-type-parameter": "error",
      "automation/no-switch": "error",
      "automation/no-type-assertion": "error",
      "automation/no-typeof-object": "error",
      "automation/no-try-catch": "error",
      "automation/pipe-max-arguments": "error",
      "automation/prefer-effect-match": "error",
      "automation/prefer-option-from-nullable": "error",
      "automation/prefer-tagged-error-handling": "error",
      "automation/private-function-prefix": "error",
      "automation/require-approved-ui-primitives": "error",
      "automation/require-cn-for-classname-composition": "error",
      "automation/require-context-service-in-services": "error",
      "automation/require-default-component-export": "error",
      "automation/require-tsx-in-ui-folders": "error",
      "automation/require-xstate-event-satisfies": "error",
      "anti-slop/no-comments": "error",
      "anti-slop/no-conditional-empty-object-spread": "error",
      "anti-slop/no-known-value-widening": "error",
      "anti-slop/no-module-mocking": "error",
      "anti-slop/no-object-parameters": "error",
      "anti-slop/no-reflect-apply": "error",
      "anti-slop/no-reflect-get": "error",
      "anti-slop/no-reprovide-ambient-service": "error",
      "anti-slop/no-runtime-typeof": "error",
      "anti-slop/no-shape-in-symbol-names": "error",
      "anti-slop/no-unknown-parameters": "error",
      "anti-slop/no-unknown-returns": "error",
      "anti-slop/no-unknown-type-aliases": "error",
      "anti-slop/no-unsafe-dictionary-type": "error",
      "anti-slop/no-widen-then-assert": "error",
      "anti-slop/require-safety-comment-for-type-assertion": "error",
      "anti-slop-effect/no-manual-effect-error-tag": "error",
      "anti-slop-effect/no-manual-tag-comparison": "error",
      "anti-slop-effect/no-manual-tagged-construction": "error",
      "anti-slop-effect/no-service-constructor-imports": "error",
      "anti-slop-effect/prefer-effect-match": "error",
      "better-tailwindcss/no-concatenated-classes": "error",
      "better-tailwindcss/no-conflicting-classes": "error",
      "better-tailwindcss/no-deprecated-classes": "error",
      "better-tailwindcss/no-duplicate-classes": "error",
      "better-tailwindcss/no-restricted-classes": ["error", { restrict: ["\\[[^\\]]+\\]"] }],
      "better-tailwindcss/no-unknown-classes": "error",
    },
    categories: {
      correctness: "error",
      suspicious: "error",
    },
  },
  fmt: {
    ignorePatterns: ["tools/oxlint/anti-slop/**", "tools/oxlint/automation/**"],
  },
});
